#! /bin/sh

# Change working directory to script directory.
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

echo "Pulling latest software from scanner."
git pull origin master

echo "Starting multicast listener."
python3 camera_module_listen.py
