#! /bin/sh

# Change working directory to script directory.
cd "${0%/*}"

echo "Pulling latest software from scanner."
git pull origin master

echo "Starting multicast listener."
python3 camera_module_listen.py
